feat: add pipeline notifications

diff --git a/.github/workflows/main-pipeline.yaml b/.github/workflows/main-pipeline.yaml
--- a/.github/workflows/main-pipeline.yaml
+++ b/.github/workflows/main-pipeline.yaml
@@ -82,4 +82,17 @@ jobs:
     needs: publish-docker-hub
     uses: ./.github/workflows/dast-zap-test.yml
     secrets: inherit
-# 
+
+  send-notifications:
+    needs: deploy-docker
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Deployment status
+        run: |
+          if [ "${{ needs.deploy-docker.result }}" == "success" ]; then
+            echo "✅ Deployment successful!"
+          else
+            echo "❌ Deployment failed!"
+            exit 1
+          fi
